*** Variables ***

#Admin
${admin_mail}                 sysadmin@qacoders.com
${admin_password}             1234@Test

#URL
${login_url}                  /api/login/
${user_url}                   /api/user/
${count_user_url}             /api/user/count/
${user_password_url}          /api/user/password/
${user_status_url}            /api/user/status/
${company_url}                /api/company/
${count_company_url}          /api/company/count/
${company_address_url}        /api/company/address/
${company_status_url}         /api/company/status/
${board_url}                  /api/board/
${count_board_url}            /api/board/count/

#User
${user_fullName}              Luiz Testa
${user_password}              1234@Test
${user_accessProfile}         ADMIN

#Company
${company_corporateName}      QAcoders
${company_matriz}             QAcoders-SP
${responsibleContact}         William Silva
${company_telephone}          5511987009068
${serviceDescription}         Programa de formcao
${company_zipCode}            04777001
${company_country}            Brasil
${company_city}               Sao Paulo
${company_state}              SP
${company_district}           Rua das Flores
${company_street}             Avenida Interlagos
${company_number}             50
${company_complement}         de 4503 ao fim - lado impar
