name: Robot_Framework_Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install SeleniumLibrary
        run: pip install --quiet robotframework-seleniumlibrary

      - name: Install RequestsLibrary
        run: pip install --quiet robotframework-requests

      - name: Install dependencies
        run: |
          pip install pyyaml
          pip install robotframework-faker

      - name: Read ambientes.yaml file
        id: read-ambientes
        run: echo "::set-output name=ambientes::$(cat backend/config/ambientes.yaml)"

      - name: Run backend tests
        working-directory: backend
        run: robot -d backend/log -v env:${{ steps.read-ambientes.outputs.ambientes }} tests

      - name: Run frontend tests
        working-directory: frontend
        run: robot -d frontend/log tests

      - name: Archive test reports
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: |
            backend/log
            frontend/log
