name: Robot_Framework_Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install --quiet robotframework-seleniumlibrary
          pip install --quiet robotframework-requests
          pip install --quiet robotframework-faker

      - name: Run backend tests
        working-directory: backend
        run: robot -d log/backend tests

      - name: Run frontend tests
        working-directory: frontend
        run: robot -d log/frontend tests

      - name: Merge test logs
        run: cat backend/log/*.xml frontend/log/*.xml > combined_log.xml

      - name: Archive test reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: combined_log.xml

